export const PRODUCT = {
  GET_CATEGORIES_AND_PRODUCTS: "PRODUCT::GET_CATEGORIES_AND_PRODUCTS",
  SET_SEL_CATEGORY: "PRODUCT::SET_SEL_CATEGORY",
  UPDATE_PRODUCT_MAP: "PRODUCT::UPDATE_PRODUCT_MAP",
  UPDATE_PRODUCT_LIST: "PRODUCT::UPDATE_PRODUCT_LIST",
  SET_SCROLL_REF: "PRODUCT::SET_SCROLL_REF",
  SET_VIEW_ALL:"PRODUCT::SET_VIEW_ALL",
}