export const PRODUCT = {
  GET_CATEGORIES_AND_PRODUCTS: "PRODUCT::GET_CATEGORIES_AND_PRODUCTS",
  SET_SEL_CATEGORY: "PRODUCT::SET_SEL_CATEGORY",
  UPDATE_PRODUCT_MAP: "UPDATE_PRODUCT_MAP::UPDATE_PRODUCT_MAP",
  UPDATE_PRODUCT_LIST: "UPDATE_PRODUCT_MAP::UPDATE_PRODUCT_LIST",
}